# Generated by Django 5.2.3 on 2025-07-16 02:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMesa',
            fields=[
                ('Id', models.AutoField(db_column='id_area_mesa', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='nombre', max_length=20)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
            ],
            options={
                'db_table': 'area_mesa',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('Id', models.AutoField(db_column='id_cargo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='nombre', max_length=20)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('Id', models.AutoField(db_column='id_platillo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='nombre', max_length=50)),
                ('Precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=8)),
                ('Descripcion', models.CharField(blank=True, db_column='descripcion', max_length=300, null=True)),
                ('ImagenUrl', models.ImageField(blank=True, db_column='imagen_url', default='platillos/ProductoSinFoto.png', null=True, upload_to='platillos')),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
            ],
            options={
                'db_table': 'platillo',
            },
        ),
        migrations.CreateModel(
            name='Tipoplatillo',
            fields=[
                ('Id', models.AutoField(db_column='id_tipo_platillo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='nombre', max_length=70)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
            ],
            options={
                'db_table': 'tipo_platillo',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('Id', models.AutoField(db_column='id_mesa', primary_key=True, serialize=False)),
                ('Numero', models.IntegerField(db_column='numero')),
                ('Capacidad', models.IntegerField(db_column='capacidad')),
                ('Estado', models.CharField(blank=True, choices=[('1', 'Disponible'), ('0', 'Ocupado')], db_column='estado', max_length=15, null=True)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
                ('IdAreaMesa', models.ForeignKey(db_column='id_area_mesa', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.areamesa')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(blank=True, db_column='total', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Monto', models.DecimalField(blank=True, db_column='monto', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Cambio', models.DecimalField(blank=True, db_column='cambio', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Propina', models.DecimalField(blank=True, db_column='propina', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Descuento', models.DecimalField(blank=True, db_column='descuento', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('MetodoPago', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia')], db_column='metodo_pago', default='1', max_length=10)),
                ('Estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Preparado'), ('3', 'Facturado'), ('4', 'Anulado')], db_column='estado', default='1', max_length=10)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
                ('IdMesa', models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.mesa')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('Id', models.AutoField(db_column='id_detalle_orden', primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(db_column='cantidad')),
                ('PrecioVenta', models.DecimalField(db_column='precio_venta', decimal_places=2, max_digits=8)),
                ('SubTotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=8)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
                ('IdOrden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.orden')),
                ('IdPlatillo', models.ForeignKey(db_column='id_platillo', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.platillo')),
            ],
            options={
                'db_table': 'detalle_orden',
            },
        ),
        migrations.AddField(
            model_name='platillo',
            name='IdTipoPlatillo',
            field=models.ForeignKey(db_column='id_tipo_platillo', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.tipoplatillo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('Nombres', models.CharField(db_column='nombres', default='', max_length=15)),
                ('Apellidos', models.CharField(db_column='apellidos', default='', max_length=15)),
                ('Direccion', models.CharField(blank=True, db_column='direccion', default='', max_length=120, null=True)),
                ('Telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], db_column='es_activo', default='1', max_length=1)),
                ('IdCargo', models.ForeignKey(db_column='id_cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.cargo', verbose_name='Cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='IdUsuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
