# Generated by Django 5.2.3 on 2025-07-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Estado',
            field=models.CharField(choices=[('0', 'Facturado'), ('1', 'Pendiente'), ('2', 'Anulado'), ('4', 'Preparado')], db_column='estado', default='1', max_length=10),
        ),
    ]
