# Generated by Django 5.2.3 on 2025-07-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areamesa',
            options={'verbose_name_plural': 'AreaMesa'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name_plural': 'Cargo'},
        ),
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name_plural': 'DetalleOrden'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name_plural': 'Mesa'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Orden'},
        ),
        migrations.AlterModelOptions(
            name='platillo',
            options={'verbose_name_plural': 'Platillo'},
        ),
        migrations.AlterModelOptions(
            name='tipoplatillo',
            options={'verbose_name_plural': 'TipoPlatillo'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuario'},
        ),
    ]
