# Generated by Django 5.2.3 on 2025-07-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_areamesa_options_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='SubTotal',
            field=models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=8),
        ),
    ]
