# Generated by Django 5.2.3 on 2025-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_detalleorden_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='Capacidad',
            field=models.IntegerField(blank=True, db_column='capacidad', null=True),
        ),
    ]
