# Generated by Django 5.2.3 on 2025-08-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_mesa_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='ImagenUrl',
            field=models.ImageField(db_column='imagen_url', default='platillos/ProductoSinFoto.png', upload_to='platillos'),
        ),
    ]
