# Generated by Django 5.2.3 on 2025-08-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_platillo_imagenurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Estado',
            field=models.CharField(choices=[('0', 'Facturado'), ('1', 'Pendiente'), ('2', 'Anulado'), ('3', 'Preparado')], db_column='estado', default='1', max_length=10),
        ),
    ]
