# Generated by Django 5.2.3 on 2025-11-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='AreaDeMesa',
            field=models.CharField(blank=True, db_column='area_de_mesa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='Banco',
            field=models.CharField(blank=True, choices=[('0', 'Lafise'), ('1', 'Banpro'), ('2', 'BAC'), ('3', 'Ficohsa'), ('4', 'Avanz'), ('5', 'Banco Atlántida'), ('6', 'BFP'), ('7', 'FDL')], db_column='banco', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='Motivo',
            field=models.CharField(blank=True, db_column='motivo', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='NumRef',
            field=models.CharField(blank=True, db_column='num_ref', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='areamesa',
            name='Nombre',
            field=models.CharField(db_column='nombre', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='IdOrden',
            field=models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Detalles', to='Application.orden'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='IdAreaMesa',
            field=models.ForeignKey(db_column='id_area_mesa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mesas', to='Application.areamesa'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='Estado',
            field=models.CharField(choices=[('0', 'Facturado'), ('1', 'Pendiente'), ('2', 'Anulado'), ('3', 'Preparado'), ('4', 'EnPreparacion')], db_column='estado', default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='IdTipoPlatillo',
            field=models.ForeignKey(db_column='id_tipo_platillo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Platillos', to='Application.tipoplatillo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='IdCargo',
            field=models.ForeignKey(db_column='id_cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuarios', to='Application.cargo', verbose_name='Cargo'),
        ),
        migrations.CreateModel(
            name='MesasPorOrden',
            fields=[
                ('Id', models.AutoField(db_column='id_mesas_por_orden', primary_key=True, serialize=False)),
                ('EsActivo', models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=10)),
                ('IdMesa', models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mesas', to='Application.mesa')),
                ('IdOrden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.orden')),
            ],
            options={
                'verbose_name_plural': 'MesasPorOrden',
                'db_table': 'mesas_por_orden',
            },
        ),
    ]
