# Generated by Django 5.2.3 on 2025-11-02 03:17

from django.db import migrations

def mover_mesas_a_mesas_por_orden(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')
    MesasPorOrden = apps.get_model('Application', 'MesasPorOrden')

    # Iteramos por todas las órdenes que tengan IdMesa no nulo
    for orden in Orden.objects.exclude(IdMesa=None):
        MesasPorOrden.objects.create(
            IdOrden_id=orden.Id,
            IdMesa_id=orden.IdMesa_id,
            EsActivo="1"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_orden_areademesa_orden_banco_orden_descripcion_and_more'),
    ]

    operations = [
        migrations.RunPython(mover_mesas_a_mesas_por_orden),
    ]
