# Generated by Django 5.2.3 on 2025-11-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_auto_20251101_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='IdMesa',
        ),
    ]
