# Generated by Django 5.2.3 on 2025-11-03 02:39

from django.db import migrations

def actualizar_area_de_mesa(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')
    Mesa = apps.get_model('Application', 'Mesa')
    MesasPorOrden = apps.get_model('Application', 'MesasPorOrden')

    # Recorremos todas las órdenes existentes
    for orden in Orden.objects.all():
        # Obtenemos la primera mesa asociada (todas deberían pertenecer a la misma área)
        mesa_por_orden = MesasPorOrden.objects.filter(IdOrden_id=orden.Id).first()
        if mesa_por_orden:
            try:
                mesa = Mesa.objects.get(pk=mesa_por_orden.IdMesa_id)
                if mesa.IdAreaMesa:
                    orden.AreaDeMesa = mesa.IdAreaMesa.Nombre
                    orden.save(update_fields=['AreaDeMesa'])
            except Mesa.DoesNotExist:
                pass
            
def revertir_migracion(apps, schema_editor):
    # Si necesitás revertir, simplemente vacía el campo
    Orden = apps.get_model('Application', 'Orden')
    Orden.objects.update(AreaDeMesa=None)

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_remove_orden_idmesa'),
    ]

    operations = [
        migrations.RunPython(actualizar_area_de_mesa, reverse_code=revertir_migracion)
    ]
