# Generated by Django 5.2.3 on 2025-11-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_auto_20251102_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaspororden',
            name='IdMesa',
            field=models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.mesa'),
        ),
        migrations.AlterField(
            model_name='mesaspororden',
            name='IdOrden',
            field=models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mesas', to='Application.orden'),
        ),
    ]
