# Generated by Django 5.2.3 on 2025-11-26 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_alter_mesaspororden_idmesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='UltimaModificacion',
            field=models.DateTimeField(auto_now_add=True, db_column='ultima_modificacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
