# Generated by Django 5.2.3 on 2025-11-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_orden_ultimamodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='FueEditada',
            field=models.BooleanField(db_column='fue_editada', default=False, null=True),
        ),
    ]
