# Generated by Django 5.2.3 on 2025-11-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_orden_fueeditada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='IdAreaDeMesa',
            field=models.ForeignKey(blank=True, db_column='id_area_de_mesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Application.areamesa'),
        ),
    ]
