# Generated by Django 5.2.3 on 2025-11-26 13:51

from django.db import migrations

def asignar_area_mesa(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')
    AreaMesa = apps.get_model('Application', 'AreaMesa')

    # Recorrer todas las órdenes
    for orden in Orden.objects.all():
        if orden.AreaDeMesa:
            # Buscar área por nombre
            area = AreaMesa.objects.filter(Nombre=orden.AreaDeMesa).first()
            if area:
                orden.IdAreaDeMesa_id = area.Id
                orden.save(update_fields=["IdAreaDeMesa"])

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_orden_idareademesa'),
    ]

    operations = [
        migrations.RunPython(asignar_area_mesa)
    ]
