# Generated by Django 5.2.3 on 2025-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_auto_20251126_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, null=True, unique=True),
        ),
    ]
