# Generated by Django 5.2.3 on 2025-12-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_column='email', default=None, max_length=254, null=True, unique=True),
        ),
    ]
