# Generated by Django 5.2.3 on 2025-12-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Banco',
            field=models.CharField(blank=True, choices=[('1', 'Lafise'), ('2', 'Banpro'), ('3', 'BAC'), ('4', 'Ficohsa'), ('5', 'Avanz'), ('6', 'Banco Atlántida'), ('7', 'BFP'), ('8', 'FDL')], db_column='banco', max_length=10, null=True),
        ),
    ]
