# Generated by Django 5.2.3 on 2025-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_alter_orden_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='DesdeEdicion',
            field=models.BooleanField(db_column='desde_edicion', default=False, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='DescripcionEdicion',
            field=models.CharField(blank=True, db_column='descripcion_edicion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='MetodoPago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia'), ('4', 'EfectivoYTarjeta')], db_column='metodo_pago', default='1', max_length=10),
        ),
    ]
