# Generated by Django 5.2.3 on 2025-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_detalleorden_desdeedicion_orden_descripcionedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='DescripcionEdicion',
            field=models.CharField(blank=True, db_column='descripcion_edicion', max_length=200, null=True),
        ),
    ]
