# Generated by Django 5.2.3 on 2025-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_alter_orden_descripcionedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='MontoRestante',
            field=models.DecimalField(blank=True, db_column='monto_restante', decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
