# Generated by Django 5.2.3 on 2026-01-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0022_orden_montorestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='EsNuevo',
            field=models.BooleanField(db_column='es_nuevo', default=False, null=True),
        ),
    ]
