# Generated by Django 5.2.3 on 2026-01-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_detalleorden_esnuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='EsEliminado',
            field=models.BooleanField(db_column='es_eliminado', default=False, null=True),
        ),
    ]
