# Generated by Django 5.2.3 on 2026-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0024_detalleorden_eseliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.CharField(blank=True, db_column='direccion', default='', max_length=200, null=True),
        ),
    ]
