# Generated by Django 5.2.3 on 2026-01-09 00:37

from django.db import migrations

def asignar_area_mesa(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')
    AreaMesa = apps.get_model('Application', 'AreaMesa')

    # Órdenes sin IdAreaDeMesa pero con texto en AreaDeMesa
    ordenes = Orden.objects.filter(
        IdAreaDeMesa__isnull=True,
        AreaDeMesa__isnull=False
    ).exclude(AreaDeMesa="")

    for orden in ordenes:
        # Normalizamos el texto por seguridad
        nombre_area = orden.AreaDeMesa.strip()

        try:
            area = AreaMesa.objects.get(
                Nombre__iexact=nombre_area,
                EsActivo="1"
            )

            orden.IdAreaDeMesa = area
            orden.save(update_fields=['IdAreaDeMesa'])

        except AreaMesa.DoesNotExist:
            # No existe un área con ese nombre → se ignora
            pass

        except AreaMesa.MultipleObjectsReturned:
            # Si hay duplicados, tomamos el primero
            area = AreaMesa.objects.filter(
                Nombre__iexact=nombre_area,
                EsActivo="1"
            ).first()

            orden.IdAreaDeMesa = area
            orden.save(update_fields=['IdAreaDeMesa'])

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0025_alter_usuario_direccion'),
    ]

    operations = [
        migrations.RunPython(asignar_area_mesa),
    ]
