# Generated by Django 5.2.3 on 2026-01-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0026_fix_area_mesa_en_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='TotalPagar',
            field=models.DecimalField(blank=True, db_column='total_pagar', decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
