# Generated by Django 5.2.3 on 2026-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0027_remove_orden_montorestante_orden_segundomonto_and_more'),
    ]

    operations = [
        # AddField removido: ya fue creado en 0027
    ]
