# Generated by Django 5.2.3 on 2026-01-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0028_feat_total_pagar_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='MontoRestante',
            new_name='SegundoMonto',
        ),
    ]
