# Generated by Django 5.2.3 on 2026-01-16 23:52

from django.db import migrations

def rellenar_total_pagar(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')

    for orden in Orden.objects.only('Id', 'Total', 'Descuento', 'Propina'):
        total = orden.Total or 0
        descuento = orden.Descuento or 0   # ya viene negativo
        propina = orden.Propina or 0

        orden.TotalPagar = total + descuento + propina
        orden.save(update_fields=['TotalPagar'])

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_remove_orden_montorestante_orden_segundomonto'),
    ]

    operations = [
        migrations.RunPython(rellenar_total_pagar)
    ]
