# Generated by Django 5.2.3 on 2026-01-17 00:09

from django.db import migrations

def poner_total_pagar_cero(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')

    # Estados que NO son "registrado / facturado"
    ordenes = Orden.objects.exclude(Estado="0").only('Id')

    for orden in ordenes:
        orden.TotalPagar = 0
        orden.save(update_fields=['TotalPagar'])

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0030_rellenar_total_pagar'),
    ]

    operations = [
        migrations.RunPython(poner_total_pagar_cero)
    ]
