# Generated by Django 5.2.3 on 2026-01-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_total_pagar_cero_no_registradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='DebeCambiarPass',
            field=models.BooleanField(db_column='debe_cambiar_pass', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='Estado',
            field=models.CharField(choices=[('0', 'Registrado'), ('1', 'Pendiente'), ('2', 'Anulado'), ('3', 'Preparado'), ('4', 'En preparación')], db_column='estado', default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='MetodoPago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia'), ('4', 'Efectivo y tarjeta')], db_column='metodo_pago', default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='SegundoMonto',
            field=models.DecimalField(blank=True, db_column='segundo_monto', decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
