# Generated by Django 5.2.3 on 2026-01-29 04:21

from django.db import migrations

def set_metodo_pago_na(apps, schema_editor):
    Orden = apps.get_model('Application', 'Orden')

    Orden.objects.filter(Estado="2").update(MetodoPago="5")


def reverse_set_metodo_pago_na(apps, schema_editor):
    # Opcional: no hacemos rollback porque no sabemos el método original
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_usuario_debecambiarpass_alter_orden_estado_and_more'),
    ]

    operations = [
        migrations.RunPython(set_metodo_pago_na, reverse_set_metodo_pago_na)
    ]
