# Generated by Django 5.2.3 on 2026-01-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0033_actualizar_metodo_pago_anuladas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='DescripcionEdicion',
            field=models.CharField(blank=True, db_column='descripcion_edicion', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='Estado',
            field=models.CharField(choices=[('0', 'Pago registrado'), ('1', 'Pendiente'), ('2', 'Anulada'), ('3', 'Preparada'), ('4', 'En preparación')], db_column='estado', default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='MetodoPago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia'), ('4', 'Efectivo y tarjeta'), ('5', 'N/A')], db_column='metodo_pago', default='5', max_length=10),
        ),
    ]
