# Generated by Django 5.2.3 on 2026-02-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0034_alter_orden_descripcionedicion_alter_orden_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=6)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaExpiracion', models.DateTimeField()),
                ('Usado', models.BooleanField(default=False)),
                ('Usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='otps_forgot_pass', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_forgot_pass',
            },
        ),
    ]
