# Generated by Django 5.2.3 on 2026-02-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0035_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
    ]
