# Generated by Django 5.2.3 on 2026-02-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0036_alter_otp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='Codigo',
            field=models.CharField(db_column='codigo', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='FechaExpiracion',
            field=models.DateTimeField(db_column='fecha_expiracion'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Id',
            field=models.AutoField(db_column='id_otp', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Usado',
            field=models.BooleanField(db_column='usado', default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='Usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
