# Generated by Django 5.2.3 on 2026-02-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0037_alter_otp_codigo_alter_otp_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='descripcion', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='Motivo',
            field=models.CharField(blank=True, db_column='motivo', max_length=150, null=True),
        ),
    ]
