# Generated by Django 5.2.3 on 2026-05-11 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0038_alter_orden_descripcion_alter_orden_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('MontoInicial', models.DecimalField(blank=True, db_column='monto_inicial', decimal_places=2, default=0, max_digits=8, null=True)),
                ('MontoFinalTeorico', models.DecimalField(blank=True, db_column='monto_final_teorico', decimal_places=2, default=0, max_digits=8, null=True)),
                ('MontoFinalReal', models.DecimalField(blank=True, db_column='monto_final_real', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Diferencia', models.DecimalField(blank=True, db_column='diferencia', decimal_places=2, default=0, max_digits=8, null=True)),
                ('Estado', models.CharField(choices=[('0', 'No iniciado'), ('1', 'Iniciado'), ('2', 'Cerrado')], db_column='estado', default='0', max_length=10)),
                ('IdUsuarioApertura', models.ForeignKey(blank=True, db_column='id_usuario_apertura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_apertura', to=settings.AUTH_USER_MODEL)),
                ('IdUsuarioCierre', models.ForeignKey(blank=True, db_column='id_usuario_cierre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Arqueo',
                'db_table': 'arqueo',
            },
        ),
    ]
