# Generated by Django 5.2.3 on 2026-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0039_arqueo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='Fecha',
            field=models.DateField(auto_now_add=True, db_column='fecha'),
        ),
    ]
