# Generated by Django 5.2.3 on 2026-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0040_alter_arqueo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='Diferencia',
            field=models.DecimalField(blank=True, db_column='diferencia', decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
