# Generated by Django 5.2.3 on 2026-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0041_alter_arqueo_diferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueo',
            name='HoraApertura',
            field=models.TimeField(blank=True, db_column='hora_apertura', default=None, null=True),
        ),
        migrations.AddField(
            model_name='arqueo',
            name='HoraCierre',
            field=models.TimeField(blank=True, db_column='hora_cierre', default=None, null=True),
        ),
    ]
