# Generated by Django 5.2.3 on 2026-06-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0042_arqueo_horaapertura_arqueo_horacierre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='AreaDeMesa',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='IdAreaDeMesa',
        ),
    ]
