# Generated by Django 5.2.3 on 2026-06-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0043_remove_orden_areademesa_remove_orden_idareademesa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platillo',
            table='consumible',
        ),
        migrations.AlterModelTable(
            name='tipoplatillo',
            table='tipo_consumible',
        ),
    ]
