# Generated by Django 5.2.3 on 2026-06-30 01:16

from django.db import migrations

def copiar_datos_a_nativos(apps, schema_editor):
    Usuario = apps.get_model('Application', 'Usuario')
    
    for usuario in Usuario.objects.all():
        # Copiar textos
        usuario.first_name = usuario.Nombres
        usuario.last_name = usuario.Apellidos
        
        # Convertir el CharField ("1"/"0") al BooleanField nativo de Django (True/False)
        usuario.is_active = (usuario.EsActivo == "1")
        
        # Guardamos usando un update específico para no disparar señales ni validaciones
        usuario.save(update_fields=['first_name', 'last_name', 'is_active'])

def revertir_copia(apps, schema_editor):
    Usuario = apps.get_model('Application', 'Usuario')
    for usuario in Usuario.objects.all():
        usuario.Nombres = usuario.first_name
        usuario.Apellidos = usuario.last_name
        usuario.EsActivo = "1" if usuario.is_active else "0"
        usuario.save(update_fields=['Nombres', 'Apellidos', 'EsActivo'])

class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0044_alter_platillo_table_alter_tipoplatillo_table'),
    ]

    operations = [
        migrations.RunPython(copiar_datos_a_nativos, revertir_copia),
    ]
