# Generated by Django 5.2.3 on 2026-06-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0045_auto_20260629_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='EsActivo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Nombres',
        ),
    ]
