# Generated by Django 5.2.3 on 2026-06-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0046_remove_usuario_apellidos_remove_usuario_esactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamesa',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='mesaspororden',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='orden',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
    ]
