# Generated by Django 5.2.3 on 2026-06-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0047_alter_areamesa_esactivo_alter_cargo_esactivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platillo',
            options={'verbose_name_plural': 'Consumible'},
        ),
        migrations.AlterField(
            model_name='platillo',
            name='Id',
            field=models.AutoField(db_column='id_consumible', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='IdTipoPlatillo',
            field=models.ForeignKey(db_column='id_tipo_consumible', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Platillos', to='Application.tipoplatillo'),
        ),
    ]
