# Generated by Django 5.2.3 on 2026-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0048_alter_platillo_options_alter_platillo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoplatillo',
            options={'verbose_name_plural': 'TipoConsumible'},
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='Id',
            field=models.AutoField(db_column='id_tipo_consumible', primary_key=True, serialize=False),
        ),
    ]
