# Generated by Django 5.2.3 on 2026-07-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0049_alter_tipoplatillo_options_alter_tipoplatillo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='EsActivo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Eliminado')], db_column='es_activo', default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='IdPlatillo',
            field=models.ForeignKey(db_column='id_consumible', on_delete=django.db.models.deletion.DO_NOTHING, to='Application.platillo'),
        ),
    ]
