# Generated by Django 5.2.3 on 2026-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0050_alter_detalleorden_esactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamesa',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='mesaspororden',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='EsActivo',
            field=models.BooleanField(db_column='es_activo', default=True),
        ),
    ]
