# Generated by Django 5.2.3 on 2026-07-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0051_alter_areamesa_esactivo_alter_cargo_esactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='Id',
            field=models.AutoField(db_column='id_arqueo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='Id',
            field=models.AutoField(db_column='id_orden', primary_key=True, serialize=False),
        ),
    ]
